apiVersion: v1
kind: Service
metadata:
  name: localhost
  labels:
    app: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      nodePort: 30000
      port: 3000
      targetPort: 3000
